version: "3.8"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8080

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "3305:8080"
